[package]
name = "xtask"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
futures-util = "0.3"
reqwest = { version = "0.12", default-features = false, features = ["brotli", "gzip", "http2", "json", "rustls-tls"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
tokio = { version = "1", features = ["fs", "macros", "rt-multi-thread", "time"] }
walkdir = "2"

[lints]
workspace = true
