[package]
name = "r-metadata"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Semantic values used by R package metadata"
documentation = "https://docs.rs/r-metadata"
readme = "README.md"
keywords = ["r", "metadata", "cran", "parser"]
categories = ["parser-implementations"]

[dependencies]
thiserror.workspace = true
url.workspace = true

[dev-dependencies]
static_assertions.workspace = true

[lints]
workspace = true
